language: cpp
dist: trusty
sudo: required

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - git clone -n https://github.com/kupix/bitstreams.git
  - cd bitstreams
  - git checkout b19d683
  - cd ..
  # - ./turing/turing-exe signature ../test/
  - ./turing/turing-exe testdecode
