language: generic
sudo: required

os:
  - linux
  - osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - git clone -n https://github.com/kupix/bitstreams.git
  - cd bitstreams
  - git checkout b19d683
  - cd ..
  # - ./turing/turing-exe signature ../test/
  - ./turing/turing-exe testdecode
