language: generic
sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

before_script:
  - mkdir build
  - git clone -n https://github.com/kupix/bitstreams.git
  - cd bitstreams
  - git checkout b19d683

script:
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=g++-5 -DCMAKE_C_COMPILER=gcc-5 ..
  - make

after_script:
  # - ./turing/turing-exe signature ../test/
  - ./turing/turing-exe testdecode
