language: cpp
dist: trusty
sudo: required

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - git clone -n https://github.com/kupix/bitstreams.git
  - cd bitstreams
  - git checkout b19d683
  - cd ..
  # - ./turing/turing-exe signature ../test/
  - ./turing/turing-exe testdecode
